# Generated by Django 5.1.6 on 2025-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
